// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmazujvlrdmfxohqavfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtYXp1anZscmRtZnhvaHFhdmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTkxMDMsImV4cCI6MjA1MjUzNTEwM30.p-BTopieRbWHxJg8K9LiKW28iGpHKDukq8ie482keO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);